ProviderPortal/Controllers/ApprenticeshipController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Tribal.SkillsFundingAgency.ProviderPortal.Classes;
using Tribal.SkillsFundingAgency.ProviderPortal.Entities;
using Tribal.SkillsFundingAgency.ProviderPortal.Models;

namespace Tribal.SkillsFundingAgency.ProviderPortal.Controllers
{
    public class ApprenticeshipController : BaseController
    {
        //
        // GET: /Apprenticeship
        [PermissionAuthorize(Permission.PermissionName.CanViewProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        [PermissionAuthorize(Permission.PermissionName.CanViewProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult List(Int32? locationId)
        {
            var model = new ApprenticeshipListViewModel();
            if (locationId.HasValue)
            {
                if (model.Search == null)
                {
                    model.Search = new ApprenticeshipSearchViewModel();
                }
                model.Search.LocationId = locationId;
            }
            model.Populate(db);
            return View(model);
        }

        [PermissionAuthorize(Permission.PermissionName.CanViewProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        [HttpPost]
        public ActionResult List(ApprenticeshipListViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Populate(db);
            }
            return View(model);
        }

        [PermissionAuthorize(Permission.PermissionName.CanEditProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Create()
        {
            var model = new AddEditApprenticeshipViewModel().Populate(db);
            ModelState.Clear();
            return View(model);
        }

        [PermissionAuthorize(Permission.PermissionName.CanEditProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        [HttpPost]
        public ActionResult Create(AddEditApprenticeshipViewModel model)
        {
            model.ApprenticeshipId = 0;
            RemoveSpellCheckHTMLFromMarketingInformation(model);
            model.Validate(db, ModelState);
            if (ModelState.IsValid)
            {
                var apprenticeship = model.ToEntity(db);
                db.Apprenticeships.Add(apprenticeship);
                db.SaveChanges();
                
                List<String> messages = model.GetWarningMessages(db);
                if (messages.Count == 0)
                {
                    ShowGenericSavedMessage();
                }
                else
                {
                    // Add a blank entry at the beginning so the String.Join starts with <br /><br />
                    messages.Insert(0, "");
                    SessionMessage.SetMessage(AppGlobal.Language.GetText(this, "SaveSuccessfulWithWarnings", "Your changes were saved successfully with the following warnings:") + String.Join("<br /><br />", messages), SessionMessageType.Success);
                }

                return Request.Form["Create"] != null
                    ? RedirectToAction("List")
                    : RedirectToAction("Create", "DeliveryLocation", new {id = apprenticeship.ApprenticeshipId});
            }
            return View(model);
        }

        [PermissionAuthorize(Permission.PermissionName.CanEditProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Edit(Int32? id)
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Create");
            }

            if (!db.Providers.Any(x => x.ProviderId == userContext.ItemId.Value)
                || !db.Apprenticeships.Any(x => x.ApprenticeshipId == id && x.ProviderId == userContext.ItemId.Value))
            {
                return HttpNotFound();
            }

            var model = new AddEditApprenticeshipViewModel();
            model = model.Populate(id.Value, db);
            return View(model);
        }

        [PermissionAuthorize(Permission.PermissionName.CanEditProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        [HttpPost]
        public ActionResult Edit(Int32 id, AddEditApprenticeshipViewModel model)
        {
            if (!db.Providers.Any(x => x.ProviderId == userContext.ItemId.Value)
                || !db.Apprenticeships.Any(x => x.ApprenticeshipId == id && x.ProviderId == userContext.ItemId.Value)
                || model.ApprenticeshipId != id)
            {
                return HttpNotFound();
            }

            RemoveSpellCheckHTMLFromMarketingInformation(model);

            model.Validate(db, ModelState);
            if (ModelState.IsValid)
            {
                model.ToEntity(db);
                db.SaveChanges();

                List<String> messages = model.GetWarningMessages(db);
                if (messages.Count == 0)
                {
                    ShowGenericSavedMessage();
                }
                else
                {
                    // Add a blank entry at the beginning so the String.Join starts with <br /><br />
                    messages.Insert(0, "");
                    SessionMessage.SetMessage(AppGlobal.Language.GetText(this, "SaveSuccessfulWithWarnings", "Your changes were saved successfully with the following warnings:") + String.Join("<br /><br />", messages), SessionMessageType.Success);
                }
                
                return RedirectToAction("List");
            }
            var deliveryLocations = new DeliveryLocationListViewModel();
            model.DeliveryLocations = deliveryLocations.Populate(id, db);
            return View(model);
        }

        [HttpGet]
        [PermissionAuthorize(Permission.PermissionName.CanViewProviderApprenticeship, Permission.PermissionName.CanEditProviderApprenticeship)]
        public ActionResult View(Int32 id)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                return HttpNotFound();
            }

            Apprenticeship apprenticeship = db.Apprenticeships.FirstOrDefault(x => x.ApprenticeshipId == id);
            if (apprenticeship == null || apprenticeship.ProviderId != userContext.ItemId)
            {
                return HttpNotFound();
            }

            ViewApprenticeshipModel model = new ViewApprenticeshipModel(apprenticeship);

            return View(model);
        }

        [HttpPost]
        [PermissionAuthorize(Permission.PermissionName.CanEditProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public NewtonsoftJsonResult ArchiveSelected(String apprenticeshipIds)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                throw new Exception("");
            }

            var archivedIds = new List<Int32>();
            foreach (String id in apprenticeshipIds.Split(','))
            {
                Int32 apprenticeshipId;
                if (Int32.TryParse(id, out apprenticeshipId))
                {
                    var apprenticeship = db.Apprenticeships.Find(apprenticeshipId);
                    if (apprenticeship.ProviderId == userContext.ItemId &&
                        apprenticeship.RecordStatusId != (Int32) Constants.RecordStatus.Archived)
                    {
                        apprenticeship.Archive(db);
                        archivedIds.Add(apprenticeshipId);
                    }
                }
            }
            if (archivedIds.Count > 0)
            {
                db.SaveChanges();
            }

            return Json(archivedIds.ToArray());
        }

        [HttpPost]
        [PermissionAuthorize(Permission.PermissionName.CanEditProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public NewtonsoftJsonResult UnarchiveSelected(String apprenticeshipIds)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                throw new Exception("");
            }

            var unarchivedIds = new List<Int32>();
            foreach (String id in apprenticeshipIds.Split(','))
            {
                Int32 apprenticeshipId;
                if (Int32.TryParse(id, out apprenticeshipId))
                {
                    var apprenticeship = db.Apprenticeships.Find(apprenticeshipId);
                    if (apprenticeship.ProviderId == userContext.ItemId &&
                        apprenticeship.RecordStatusId == (Int32) Constants.RecordStatus.Archived)
                    {
                        apprenticeship.Unarchive(db);
                        unarchivedIds.Add(apprenticeshipId);
                    }
                }
            }
            if (unarchivedIds.Count > 0)
            {
                db.SaveChanges();
            }

            return Json(unarchivedIds.ToArray());
        }

        [HttpPost]
        [PermissionAuthorize(Permission.PermissionName.CanEditProviderApprenticeship)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Archive(Int32 id)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                return HttpNotFound();
            }

            Apprenticeship apprenticeship = db.Apprenticeships.Find(id);

ProviderPortal/Views/Apprenticeship/Create.cshtml
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.AddEditApprenticeshipViewModel
@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "Add New Apprenticeship");
}

<h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "Add New Apprenticeship")</h2>

@Html.Partial("_EditApprenticeship", Model)

@section Scripts {   
    @Html.Partial("_EditApprenticeshipScripts", Model)
}

ProviderPortal/Views/Apprenticeship/Edit.cshtml
@using Permission = Tribal.SkillsFundingAgency.ProviderPortal.Permission
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.AddEditApprenticeshipViewModel
@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "Edit Apprenticeship");
}

<h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "Edit Apprenticeship")</h2>

@Html.Partial("_EditApprenticeship", Model)

<fieldset>
    <legend>@AppGlobal.Language.GetText(this, "DeliveryLocations", "Delivery Locations")</legend>
    @if (Permission.HasPermission(false, false, Permission.PermissionName.CanEditProviderApprenticeship))
    {
        <a href="@Url.Action("Create", "DeliveryLocation", new { Id = @Model.ApprenticeshipId })" style="float: right; margin-top: -45px;">@AppGlobal.Language.GetText(this, "AddDeliveryLocation", "Add New Delivery Location")</a>
    }
    <div class="col-md-12">
        @Html.Partial("DisplayTemplates/_ListDeliveryLocations", Model.DeliveryLocations.Items)
    </div>
</fieldset>

@section Scripts {
    @Html.Partial("_EditApprenticeshipScripts", Model)
}

ProviderPortal/Views/Apprenticeship/List.cshtml
@using Tribal.SkillsFundingAgency.ProviderPortal.Controllers
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.ApprenticeshipListViewModel
@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "View all Apprenticeships");
    Boolean showDataReadyForQAButton = new ProviderController().showDataReadyForQAButton();
    Boolean showNumberOfApprenticeshipsQAd = Permission.HasPermission(false, false, Permission.PermissionName.CanQAApprenticeships); // && Model.DataReadyForQA;
}

<h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "View all Apprenticeships")</h2>

@if (Model.DisplayNotPublishedBanner)
{
    <div class="warning">
        @if (Permission.HasPermission(false, false, Permission.PermissionName.CanEditProvider))
        {
            @Html.Raw(AppGlobal.Language.GetText(this, "NoProviderApprenticeshipContractWithEditLink", @"Apprenticeship information will not be displayed on the digital apprenticeship service website as 'Current contract with the SFA' is not checked. Click <a href=""/Provider/Edit#ApprenticeshipDelivery"">Edit Provider</a> to enter it."))
        }
        else
        {
            @Html.Raw(AppGlobal.Language.GetText(this, "NoProviderApprenticeshipContractWithoutEditLink", "Apprenticeship information will not be displayed on the digital apprenticeship service website as 'Current contract with the SFA' is not checked."))
        }
    </div>
}

<div class="col-md-12">
    
    <div class="col-md-3 sidebar">
        @using (Html.BeginForm())
        {          
            @Html.HiddenFor(m => m.Search.FrameworkOrStandardId)  
            <h4>@AppGlobal.Language.GetText(this, "ApprenticeshipSearchOptions", "Apprenticeship search options")</h4>
        
            <div class="form-group">
                @Html.LanguageLabelFor(m => m.Search.FrameworkOrStandard, new {@class = "control-label"})
                <br />
                @Html.EditorFor(model => model.Search.FrameworkOrStandard, new { htmlAttributes = new {@class = "form-control"} })
            </div>

            <div class="form-group">
                @Html.LanguageLabelFor(m => m.Search.LocationId, new {@class = "control-label"})
                <br />
                @Html.DropDownListFor(m => m.Search.LocationId, Model.Search.Locations, AppGlobal.Language.GetText(this, "PleaseSelect", "Please Select"), new {@class = "form-control"})
            </div>

            <div class="form-group">
                @Html.LanguageLabelFor(m => m.Search.DeliveryModeId, new {@class = "control-label"})
                <br />
                @Html.DropDownListFor(m => m.Search.DeliveryModeId, Model.Search.DeliveryModes, AppGlobal.Language.GetText(this, "PleaseSelect", "Please Select"), new {@class = "form-control"})
            </div>
            
            <div class="form-group">
                <div style="text-align: right;">
                    <input type="submit" value="@AppGlobal.Language.GetText(this, "Submit", "Search")" class="btn btn-default" />
                </div>
            </div>            
        }
    </div>

    <div class="col-md-9">
        @if (showNumberOfApprenticeshipsQAd)
        {
            <div class="warning">
                <span id="spanQAdApprenticeships">@Html.Raw(String.Format(AppGlobal.Language.GetText(this, "xOutOfyApprenticeshipsHaveBeenQAed", "{0} out of the {1} required apprenticeships have been quality assured."), Model.ApprenticeshipsQAed.ToString("N0"), Model.NumberOfApprenticeshipsRequiredToQA.ToString("N0")))</span>
            </div>
        }

        @if (showDataReadyForQAButton)
        {
            <div id="divDataReadyForQA2" class="pull-left" style="display: none;">
                <input id="btnDataReadyForQA2" type="button" value="@AppGlobal.Language.GetText(this, "ReadyForQAButtonText", "Ready for QA")" class="btn btn-readyforqa" />
                @if (AppGlobal.Language.GetText(this, "DataReadyForQATooltip", "") != "")
                {
                    @Html.Tooltip(AppGlobal.Language.GetText(this, "DataReadyForQATooltip", ""))
                }
            </div>
        }        
        @Html.DisplayFor(m => m.Apprenticeships, "_ListApprenticeships")
    </div>

</div>

ProviderPortal/Views/Apprenticeship/QAForComplianceFromDialog.cshtml
@using Tribal.SkillsFundingAgency.ProviderPortal.Entities
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.AddEditApprenticeshipQAForComplianceModel
@{
    Layout = null;
}
@using (Html.BeginForm("QAForComplianceFromDialog", "Apprenticeship", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.EditableDataValidationSummary(false)

        @Html.RequiredFields(new {@class = "col-md-offset-3"})
        @Html.HiddenFor(model => model.ApprenticeshipQAComplianceId)
        @Html.HiddenFor(model => model.ApprenticeshipId)

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.QAComplianceFailureReasons, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @foreach (QAComplianceFailureReason fr in Model.QAComplianceFailureReasons)
                {
                    <input id="@fr.QAComplianceFailureReasonId" title="@fr.Description" type="checkbox" name="SelectedComplianceFailureReasons" value="@fr.QAComplianceFailureReasonId" @(Model.SelectedComplianceFailureReasons.Contains(fr.QAComplianceFailureReasonId) ? "checked" : "")/>
                    <label for="@fr.QAComplianceFailureReasonId" title="@fr.Description" style="font-weight: normal;">@fr.Description</label>
                    <br/>
                }
                @Html.ValidationMessageFor(model => model.QAComplianceFailureReasons)
            </div>
        </div>

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.DetailsOfUnverifiableClaim, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @Html.EditorFor(model => model.DetailsOfUnverifiableClaim, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DetailsOfUnverifiableClaim)
            </div>
        </div>


        <div class="form-group">
            @Html.LanguageLabelFor(model => model.DetailsOfComplianceFailure, new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.DetailsOfComplianceFailure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DetailsOfComplianceFailure)
            </div>
        </div>

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.Passed, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @Html.DropDownListFor(m => m.Passed, (SelectList) ViewBag.YesNo, AppGlobal.Language.GetText(this, "PleaseSelect", "Please Select"), new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Passed)
            </div>
        </div>

        <div style="clear: both;"></div>

    </div>

    <script>
        $('.modal-dialog .glyphicon-question-sign').tooltip({ placement: "auto" });
    </script>
}

ProviderPortal/Views/Apprenticeship/QAForStyleFromDialog.cshtml
@using Tribal.SkillsFundingAgency.ProviderPortal.Entities
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.AddEditApprenticeshipQAForStyleModel
@{
    Layout = null;
}
@using (Html.BeginForm("QAForStyleFromDialog", "Apprenticeship", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.EditableDataValidationSummary(false)

        @Html.RequiredFields(new {@class = "col-md-offset-3"})
        @Html.HiddenFor(model => model.ApprenticeshipQAStyleId)
        @Html.HiddenFor(model => model.ApprenticeshipId)

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.QAStyleFailureReasons, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @foreach (QAStyleFailureReason fr in Model.QAStyleFailureReasons)
                {
                    <input id="@fr.QAStyleFailureReasonId" title="@fr.Description" type="checkbox" name="SelectedStyleFailureReasons" value="@fr.QAStyleFailureReasonId" @(Model.SelectedStyleFailureReasons.Contains(fr.QAStyleFailureReasonId) ? "checked" : "")/>
                    <label for="@fr.QAStyleFailureReasonId" title="@fr.Description" style="font-weight: normal;">@fr.Description</label>
                    <br/>
                }
                @Html.ValidationMessageFor(model => model.QAStyleFailureReasons)
            </div>
        </div>

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.Passed, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @Html.DropDownListFor(m => m.Passed, (SelectList) ViewBag.YesNo, AppGlobal.Language.GetText(this, "PleaseSelect", "Please Select"), new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Passed)
            </div>
        </div>

        <div class="form-group">
            @Html.LanguageLabelFor(m => m.DetailsOfQA, new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.DetailsOfQA, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DetailsOfQA)
            </div>
        </div>

        <div style="clear: both;"></div>

    </div>

    <script>
        $('.modal-dialog .glyphicon-question-sign').tooltip({ placement: "auto" });
    </script>
}

ProviderPortal/Views/Apprenticeship/View.cshtml
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.ViewApprenticeshipModel
@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "Apprenticeship Details");
}

<h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "Apprenticeship Details")</h2>
<h3>@Model.FrameworkOrStandard</h3>
<hr/>
<div class="col-md-12">
        
    @if (Model.DisplayNotPublishedBanner)
    {
        <div class="warning">
            @if (Permission.HasPermission(false, false, Permission.PermissionName.CanEditProvider))
            {
                @Html.Raw(AppGlobal.Language.GetText(this, "NoProviderApprenticeshipContractWithEditLink", @"Apprenticeship information will not be displayed on the digital apprenticeship service website as 'Current contract with the SFA' is not checked. Click <a href=""/Provider/Edit#ApprenticeshipDelivery"">Edit Provider</a> to enter it."))
            }
            else
            {
                @Html.Raw(AppGlobal.Language.GetText(this, "NoProviderApprenticeshipContractWithoutEditLink", "Apprenticeship information will not be displayed on the Digital Apprenticeship Service website as 'Current contract with the SFA' is not checked."))
            }
        </div>
    }

    @if (Model.RecordStatusId == (Int32) Constants.RecordStatus.Archived)
    {
        <div class="col-md-offset-2 warning">
            @Html.Raw(AppGlobal.Language.GetText(this, "ApprenticeshipArchivedWarning", "<strong>Warning:</strong> this apprenticeship is currently <strong>ARCHIVED</strong> and neither it nor any of its delivery locations will be published to the digital apprenticeship service."))
        </div>
    }
    @if (Model.RecordStatusId == (Int32) Constants.RecordStatus.Pending)
    {
        <div class="col-md-offset-2 warning">
            @Html.Raw(AppGlobal.Language.GetText(this, "ApprenticeshipPendingWarning", "<strong>Warning:</strong> this apprenticeship is currently PENDING as it does not have any delivery locations. It will not be viewable to employers on the website."))
        </div>
    }
        
    <dl class="dl-horizontal">
        
        <dt>@Html.DisplayNameFor(m => m.RecordStatusName)</dt>
        <dd>@Html.DisplayTextFor(m => m.RecordStatusName)</dd>
    
        <dt>@Html.DisplayNameFor(m => m.FrameworkOrStandard)</dt>
        <dd>@Html.DisplayTextFor(m => m.FrameworkOrStandard)</dd>

        <dt>@Html.DisplayNameFor(m => m.MarketingInformation)</dt>
        <dd>@Html.DisplayTextFor(m => m.MarketingInformation)</dd>    
    
        <dt>@Html.DisplayNameFor(m => m.Url)</dt>
        <dd>
            @if (Model.Url != null)
            {
                var prefix = Model.Url.Contains("://") ? "" : "http://";
                <a href="@prefix@Model.Url" target="_blank">@Model.Url</a>
            }
        </dd>
            
        <dt>@Html.DisplayNameFor(m => m.ContactEmail)</dt>
        <dd>
            @if (Model.ContactEmail != null)
            {
                <a href="mailto:@Model.ContactEmail" target="_blank">@Model.ContactEmail</a>
            }
        </dd>
            
        <dt>@Html.DisplayNameFor(m => m.ContactTelephone)</dt>
        <dd>@Html.DisplayTextFor(m => m.ContactTelephone)</dd>    
    
        <dt>@Html.DisplayNameFor(m => m.ContactWebsite)</dt>
        <dd>
            @if (Model.ContactWebsite != null)
            {
                var prefix = Model.ContactWebsite.Contains("://") ? "" : "http://";
                <a href="@prefix@Model.ContactWebsite" target="_blank">@Model.ContactWebsite</a>
            }
        </dd>            
    </dl>
    
    @if (Permission.HasPermission(false, false, Permission.PermissionName.CanViewApprenticeshipQA))
    {
        <fieldset>
            <legend>
                @AppGlobal.Language.GetText(this, "QualityAssurance", "Quality Assurance")
                @if (AppGlobal.Language.GetText(this, "QualityAssuranceTooltip", "") != "")
                {
                    @Html.Tooltip(AppGlobal.Language.GetText(this, "QualityAssuranceTooltip", ""))
                }
            </legend>
            <a href="@Url.Action("ViewQAHistory", "Apprenticeship", new { Id = @Model.ApprenticeshipId })" style="float: right; margin-top: -45px;">@AppGlobal.Language.GetText(this, "ViewQAHistory", "View QA History")</a>
        
            <p class="required-message col-md-offset-2">
                @if (Model.LastQAdForComplianceOn.HasValue)
                {
                    @Html.Raw(String.Format(AppGlobal.Language.GetText(this, "LastQAdForComplianceOnBy", "Last Quality Assured for Compliance on <b>{0}</b> by <b>{1}</b>."), Model.LastQAdForComplianceOn, Model.LastQAdForComplianceBy))
                }
                else
                {
                    @Html.Raw(AppGlobal.Language.GetText(this, "NeverQAdForCompliance", "Last Quality Assured for Compliance : <b>Never</b>"))
                }  
            </p>
                
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(m => m.HasBeenQAdForCompliance)</dt>
                <dd>
                    @if (Model.HasBeenQAdForCompliance)
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "Yes", "Yes"))
                    }
                    else
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "No", "No"))
                    }            
                </dd>

                <dt>@Html.DisplayNameFor(m => m.HasPassedComplianceChecks)</dt>
                <dd>
                    @if (Model.HasPassedComplianceChecks)
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "Yes", "Yes"))
                    }
                    else
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "No", "No"))
                    }
                </dd>
            </dl>
        
            <p class="required-message col-md-offset-2">
                @if (Model.LastQAdForStyleOn.HasValue)
                {
                    @Html.Raw(String.Format(AppGlobal.Language.GetText(this, "LastQAdForStyleOnBy", "Last Quality Assured for Style on <b>{0}</b> by <b>{1}</b>."), Model.LastQAdForStyleOn, Model.LastQAdForStyleBy))
                }
                else
                {
                    @Html.Raw(AppGlobal.Language.GetText(this, "NeverQAdForStyle", "Last Quality Assured for Style : <b>Never</b>"))
                }  
            </p>                
                
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(m => m.HasBeenQAdForStyle)</dt>
                <dd>
                    @if (Model.HasBeenQAdForStyle)
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "Yes", "Yes"))
                    }
                    else
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "No", "No"))
                    }            
                </dd>

                <dt>@Html.DisplayNameFor(m => m.HasPassedStyleChecks)</dt>
                <dd>
                    @if (Model.HasPassedStyleChecks)
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "Yes", "Yes"))
                    }
                    else
                    {
                        @Html.Raw(AppGlobal.Language.GetText(this, "No", "No"))
                    }
                </dd>
            </dl>

        </fieldset>
    }

    <fieldset>
        <legend>@AppGlobal.Language.GetText(this, "DeliveryLocations", "Delivery Locations")</legend>
        @if (Permission.HasPermission(false, false, Permission.PermissionName.CanEditProviderApprenticeship))
        {
            <a href="@Url.Action("Create", "DeliveryLocation", new { Id = @Model.ApprenticeshipId })" style="float: right; margin-top: -45px;">@AppGlobal.Language.GetText(this, "AddDeliveryLocation", "Add New Delivery Location")</a>
        }
        <div class="col-md-12">
            @Html.Partial("DisplayTemplates/_ListDeliveryLocations", Model.DeliveryLocations.Items)
        </div>
    </fieldset>
    
</div>