ProviderPortal/Controllers/LARSController.cs
using System;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Tribal.SkillsFundingAgency.ProviderPortal.Entities;
using Tribal.SkillsFundingAgency.ProviderPortal.Models;

namespace Tribal.SkillsFundingAgency.ProviderPortal.Controllers
{
    [ContextAuthorize(UserContext.UserContextName.Administration)]
    public class LARSController : BaseController
    {
        private static String mdbFilename = String.Empty;
        private static long mdbFileSize;

        //
        // GET: /LARS/
        [HttpGet]
        [PermissionAuthorize(Permission.PermissionName.CanUploadLARSData)]
        public ActionResult Index()
        {
            LARSUploadModel model = new LARSUploadModel();
            GetLastUploadDetails(model);
            return View(model);
        }

        [HttpPost]
        [PermissionAuthorize(Permission.PermissionName.CanUploadLARSData)]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LARSUploadModel model)
        {
            if (ModelState.IsValid)
            {
                String[] validFileTypes = { ".zip" };
                Boolean validFileType = false;
                String LARSFolder = Constants.ConfigSettings.LARSUploadVirtualDirectoryName;
                if (LARSFolder.EndsWith(@"\"))
                {
                    LARSFolder = LARSFolder.Substring(0, LARSFolder.Length - 1);
                }

                // Check if config setting is valid
                if (String.IsNullOrEmpty(LARSFolder) || !Directory.Exists(LARSFolder))
                {
                    ModelState.AddModelError("", AppGlobal.Language.GetText(this, "LARSFolderNotConfigured", "Configuration setting VirtualDirectoryNameForStoringLARSFiles is not set or is incorrect"));
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        foreach (String fileType in validFileTypes)
                        {
                            if (model.File.FileName.ToLower().EndsWith(fileType))
                            {
                                validFileType = true;
                                break;
                            }
                        }
                        if (!validFileType)
                        {
                            ModelState.AddModelError("File", AppGlobal.Language.GetText(this, "ZIPFilesOnly", "Please upload a ZIP file"));
                        }
                        else
                        {
                            String ZIPFile = String.Format("{0}/LARS.zip", LARSFolder);

                            // Save the zip file
                            model.File.SaveAs(ZIPFile);

                            // Import the file
                            ImportLARSFile(Permission.GetCurrentUserGuid().ToString(), AppGlobal.Language.GetLanguageIdForThisRequest());

                            if (ModelState.IsValid)
                            {
                                ViewBag.Message = AppGlobal.Language.GetText(this, "ImportSuccessful", "LARS Data Successfully Imported");
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        // Create a model error
                        ModelState.AddModelError("", ex.Message);
                    }

                    // Delete the existing files
                    foreach (FileInfo file in new DirectoryInfo(LARSFolder).GetFiles())
                    {
                        file.Delete();
                    }
                }
            }

            GetLastUploadDetails(model);
            return View(model);
        }

        [HttpPost]
        [PermissionAuthorize(Permission.PermissionName.CanUploadLARSData)]
        public ActionResult ClearAutomationInProgressFlag()
        {
            AutomationController.CompleteAutomatedTask(AutomationController.AutomatedTaskName.LARSImport);
            return RedirectToAction("Index");
        }

        [NonAction]
        public static void ImportLARSFile(String userId, Int32 languageId)
        {
            ProviderPortalEntities db = new ProviderPortalEntities();

            String LARSFolder = Constants.ConfigSettings.LARSUploadVirtualDirectoryName;
            if (LARSFolder.EndsWith(@"\"))
            {
                LARSFolder = LARSFolder.Substring(0, LARSFolder.Length - 1);
            }

            // Check if config setting is valid
            if (String.IsNullOrEmpty(LARSFolder) || !Directory.Exists(LARSFolder))
            {
                throw new Exception(AppGlobal.Language.GetText("LARS_ImportLARSFile_LARSFolderNotConfigured", "Configuration setting VirtualDirectoryNameForStoringLARSFiles is not set or is incorrect", false, languageId));
            }

            // Unzip the file(s) - Should only be 1 really
            foreach (String zipFile in Directory.GetFiles(LARSFolder, "*.zip"))
            {
                System.IO.Compression.ZipFile.ExtractToDirectory(zipFile, LARSFolder);
                System.IO.File.Delete(zipFile);
            }

            // Get the MDB Filename
            String[] mdbFiles = Directory.GetFiles(LARSFolder, "*.mdb");
            if (mdbFiles.GetLength(0) == 0)
            {
                throw new Exception(AppGlobal.Language.GetText("LARS_ImportLARSFile_UnableToFindMDBFile", "Unable to find MDB file in ZIP file", false, languageId));
            }

            mdbFilename = mdbFiles[0];
            mdbFileSize = new FileInfo(mdbFilename).Length;

            // Open the database
            using (SqlConnection conn = new SqlConnection(db.Database.Connection.ConnectionString))
            {
                // Open the database connection
                conn.Open();

                // Import the data
                ImportClassifications(conn, userId, db);
                ImportAwardingOrganisation(conn, userId, db);
                ImportLearningAims(conn, userId, db);
                ImportValidity(conn, userId, db);
                ImportFrameworksAndStandards(conn, userId, db);

                // Close the database
                conn.Close();
            }

            // Save metadata upload records
            db.SaveChanges();
        }

        [NonAction]
        private void GetLastUploadDetails(LARSUploadModel model)
        {
            String taskName = AutomationController.AutomatedTaskName.LARSImport.ToString();
            AutomatedTask at = db.AutomatedTasks.Where(x => x.TaskName == taskName).FirstOrDefault();
            if (at != null)
            {
                model.IsAutomationInProgress = at.InProgress;
            }

            MetadataUpload dataUpload = db.MetadataUploads.Where(m => m.MetadataUploadTypeId == (Int32)Constants.MetadataUploadType.LearningAim).OrderByDescending(m => m.CreatedDateTimeUtc).FirstOrDefault();
            if (dataUpload != null)
            {
                if (dataUpload.AspNetUser == null)
                {
                    AspNetUser user = db.AspNetUsers.Find(dataUpload.CreatedByUserId);
                    if (user != null)
                    {
                        model.LastUploadedBy = user.Name;
                    }
                }
                else
                {
                    model.LastUploadedBy = dataUpload.AspNetUser.Name ?? dataUpload.AspNetUser.Email;
                }
                model.LastUploadDateTimeUtc = dataUpload.CreatedDateTimeUtc;
                DateTime.SpecifyKind(model.LastUploadDateTimeUtc.Value, DateTimeKind.Utc);
                model.LastUploadFileName = dataUpload.FileName;
            }            
        }

        [NonAction]
        private static void ImportClassifications(SqlConnection conn, String userId, ProviderPortalEntities db)
        {
            MetadataUpload metadataUpload = new MetadataUpload
            {
                MetadataUploadTypeId = (int)Constants.MetadataUploadType.LearnDirectClassification,
                CreatedByUserId = userId,
                CreatedDateTimeUtc = DateTime.UtcNow,
                FileName = Path.GetFileName(mdbFilename),
                FileSizeInBytes = (int)mdbFileSize,
                RowsBefore = db.LearnDirectClassifications.Count()
            };
            Stopwatch sw = new Stopwatch();
            sw.Start();

            // Import Classifications
            SqlCommand comm = new SqlCommand("TRUNCATE TABLE [dbo].[Import_LearnDirectClassification];", conn);
            comm.ExecuteNonQuery();
            DataTable dt = OpenDataTable("SELECT LearnDirectClassSystemCode AS LearnDirectClassificationRef, LearnDirectClassSystemCodeDesc FROM CoreReference_LARS_LearnDirectClassSystemCode_Lookup;");
            BulkImportData(conn, dt, "[dbo].[Import_LearnDirectClassification]");
            comm = new SqlCommand("MERGE [dbo].[LearnDirectClassification] dest USING [dbo].[Import_LearnDirectClassification] source ON  dest.LearnDirectClassificationRef = source.LearnDirectClassificationRef WHEN MATCHED THEN UPDATE SET dest.LearnDirectClassSystemCodeDesc = source.LearnDirectClassSystemCodeDesc WHEN NOT MATCHED THEN INSERT (LearnDirectClassificationRef, LearnDirectClassSystemCodeDesc) VALUES (source.LearnDirectClassificationRef, source.LearnDirectClassSystemCodeDesc);", conn);
            comm.ExecuteNonQuery();

            // Update LDCS Hierarchy
            SqlCommand commSP = new SqlCommand("[dbo].[up_UpdateLDCSHierarchy]", conn)
            {
                CommandType = CommandType.StoredProcedure
            };
            commSP.ExecuteNonQuery();

            sw.Stop();
            metadataUpload.DurationInMilliseconds = (int)sw.ElapsedMilliseconds;
            metadataUpload.RowsAfter = db.LearnDirectClassifications.Count();

ProviderPortal/Views/LARS/Index.cshtml
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.LARSUploadModel
@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "Import LARS Data");
}

<h2>@AppGlobal.Language.GetText(this, "Header", "Import LARS Data")</h2>

@Html.Raw(AppGlobal.Language.GetText(this, "SubHeader", "<hr /><p>Use this page to upload new LARS data.  The file should be a zipped copy of the Access Database (MDB) version.  The latest version can be downloaded from <a href=\"https://hub.imservices.org.uk/Learning%20Aims/Downloads/Pages/default.aspx\" target=\"blank\">this page</a></p><hr />"))

@if (!String.IsNullOrEmpty(ViewBag.Message))
{
    <div class="warning">
        @Html.Raw(ViewBag.Message)
    </div>
}

@Html.EditableDataValidationSummary(false)

@using (Html.BeginForm("Index", "LARS", FormMethod.Post, new { enctype = "multipart/form-data" }))
{   
    @Html.AntiForgeryToken()
    <div class="row">
        <table class="dt-responsive table table-bordered">
            <thead>
                <tr>
                    <th class="col-md-6">
                        @AppGlobal.Language.GetText(this, "UploadSectionHeader", "Upload a new file")
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="form-group">
                            @AppGlobal.Language.GetText(this, "UploadText", "Click Browse and select your LARS data file. Click upload.")
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.File, new { type = "file", @class = "btn btn-success" })
                            @Html.ValidationMessageFor(m => m.File)
                        </div>
                        <div class="form-group">
                            <input type="submit" value="@AppGlobal.Language.GetText(this, "SubmitUpload", "Upload")" class="btn btn-success" />
                            @if (Model.IsAutomationInProgress)
                            {
                                <br /><br />
                                @Html.Raw(AppGlobal.Language.GetText(this, "ClearAutomationInProgressDescription", "There is a flag in the database which is set when the automated LARS import is in progress.  This is to prevent multiple servers in the server farm from importing the file simultaneously.  If this flag is not cleared for some reason then the automated import will not work.  The flag is currently set.  You can clear the flag by clicking on the button below but you should be sure that the automated import is complete (or has errored) before doing so.<br /><br />"))
                                <input id="btnClearAutomationInProgress" type="button" name="ClearAutomationInProgress" value="@AppGlobal.Language.GetText(this, "ClearAutomationInProcess", "Clear Automation in Progress Flag")" class="btn btn-warning" />
                            }
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}
@if (Model.LastUploadedBy != null)
{
    @Html.Raw(String.Format(AppGlobal.Language.GetText(this, "LastUploadDetails", "<span style=\"font-size: smaller;\">Last uploaded by {0} on {1}.  Filename: {2}</span>"), Model.LastUploadedBy, Model.LastUploadDateTimeLocalTime, Model.LastUploadFileName))
}

@section Scripts {

    <script type="text/javascript">

        $(document).ready(function() {

            $("#btnClearAutomationInProgress").click(function () {
                if (confirm('@AppGlobal.Language.GetText(this, "ClearAutomationInProgressFlagWarning", "Are you sure you would like clear the automation in progress flag?")') === false) {
                    return;
                }
                var url = '@Url.Action("ClearAutomationInProgressFlag", "LARS")';
                $.ajax({
                    url: url,
                    success: function() {
                        window.location.reload(true);
                    },
                    error: function() {
                        alert("Error clearing automation in progress flag");
                    },
                    cache: false,
                    type: 'POST',
                    contentType: 'application/x-www-form-urlencoded, charset=utf-8'
                });
            });

        });

    </script>

}