ProviderPortal/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Tribal.SkillsFundingAgency.ProviderPortal.Classes;
using Tribal.SkillsFundingAgency.ProviderPortal.Entities;
using Tribal.SkillsFundingAgency.ProviderPortal.Models;

namespace Tribal.SkillsFundingAgency.ProviderPortal.Controllers
{
    public class LocationController : BaseController
    {
        readonly String unableToFindLatLngMessage = AppGlobal.Language.GetText("Location_Edit_UnableToFindLatLong", "Postcode cannot be used because we are unable to find latitude and longitude information for it.");

        //
        // GET: /Location
        [HttpGet]
        [PermissionAuthorize(Permission.PermissionName.CanViewProviderLocation)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        //
        // GET: /Location/Create
        [HttpGet]
        [PermissionAuthorize(Permission.PermissionName.CanAddProviderLocation)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Create()
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                return HttpNotFound();
            }

            var model = new AddEditLocationModel
            {
                ProviderId = provider.ProviderId
            };

            // Populate drop downs
            GetLookups(model);

            ViewBag.CanProviderCreateNewLocation = CanProviderCreateNewLocation(provider, out Int32 maxNumberOfLocations);
            ViewBag.MaxNumberOfLocations = maxNumberOfLocations.ToString("N0");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorize(Permission.PermissionName.CanAddProviderLocation)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Create(AddEditLocationModel model)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                return HttpNotFound();
            }

            if (model.ProviderId != provider.ProviderId)
            {
                return HttpNotFound();
            }

            Location loc = db.Locations.FirstOrDefault(x => x.LocationName == model.LocationName && x.ProviderId == provider.ProviderId);
            if (loc != null)
            {
                ModelState.AddModelError("LocationName", AppGlobal.Language.GetText("Location_Create_DuplicateLocatioName", "The Location Name supplied is already in use."));
            }

            Address address = model.Address.ToEntity(db);
            Location locDupPostcode = db.Locations.FirstOrDefault(x => x.RecordStatusId == (int)Constants.RecordStatus.Live && x.Address.Postcode == address.Postcode && x.ProviderId == provider.ProviderId);
            if (locDupPostcode != null)
            {
                ModelState.AddModelError("Address.Postcode", AppGlobal.Language.GetText("Location_Create_DuplicatePostcode", "The postcode supplied is already in use."));
            }

            CheckMaxNumberOfLocations(provider);

            if (ModelState.IsValid)
            {
                Location location = CreateFromModel(model, provider.ProviderId);
                if (!location.Address.Latitude.HasValue)
                {
                    ModelState.AddModelError("Address.Postcode", unableToFindLatLngMessage);
                }
                else
                {
                    List<String> messages = model.GetWarningMessages();
                    if (messages.Count == 0)
                    {
                        ShowGenericSavedMessage();
                    }
                    else
                    {
                        // Add a blank entry at the beginning so the String.Join starts with <br /><br />
                        messages.Insert(0, "");
                        SessionMessage.SetMessage(AppGlobal.Language.GetText(this, "SaveSuccessfulWithWarnings", "Your changes were saved successfully with the following warnings:") + String.Join("<br /><br />", messages), SessionMessageType.Success);
                    }

                    return RedirectToAction("List");
                }
            }

            // Populate drop downs
            GetLookups(model);

            // Set this to true here so that the message doesn't appear twice
            ViewBag.CanProviderCreateNewLocation = true;

            return View(model);
        }

        [HttpGet]
        [PermissionAuthorize(Permission.PermissionName.CanAddProviderLocation)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult CreateFromDialog(Int32 id)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                return HttpNotFound();
            }

            if (id != userContext.ItemId)
            {
                return View("UnableToCreate");
            }

            var model = new AddEditLocationModel
            {
                ProviderId = provider.ProviderId,
                IsInDialog = true
            };

            // Populate drop downs
            GetLookups(model);

            ViewBag.CanProviderCreateNewLocation = CanProviderCreateNewLocation(provider, out Int32 maxNumberOfLocations);
            ViewBag.MaxNumberOfLocations = maxNumberOfLocations.ToString("N0");

            return View("Create", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorize(Permission.PermissionName.CanAddProviderLocation)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult CreateFromDialog(AddEditLocationModel model)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                return HttpNotFound();
            }

            if (model.ProviderId != provider.ProviderId)
            {
                return View("UnableToCreate");
            }

            model.IsInDialog = true;

            Location loc = db.Locations.FirstOrDefault(x => x.LocationName == model.LocationName && x.ProviderId == provider.ProviderId);
            if (loc != null)
            {
                ModelState.AddModelError("LocationName", AppGlobal.Language.GetText("Location_Create_DuplicateLocatioName", "The Location Name supplied is already in use."));
            }

            Address address = model.Address.ToEntity(db);
            Location locDupPostcode = db.Locations.FirstOrDefault(x => x.RecordStatusId == (int)Constants.RecordStatus.Live && x.Address.Postcode == address.Postcode && x.ProviderId == provider.ProviderId);
            if (locDupPostcode != null)
            {
                ModelState.AddModelError("Address.Postcode", AppGlobal.Language.GetText("Location_Create_DuplicatePostcode", "The postcode supplied is already in use."));
            }

            if (!String.IsNullOrWhiteSpace(model.Website))
            {
                model.Website = UrlHelper.GetFullUrl(model.Website);
                Boolean websiteValid = false;
                Uri uriResult;
                if (Uri.TryCreate(model.Website, UriKind.Absolute, out uriResult))
                {
                    if (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps)
                    {
                        websiteValid = true;
                    }
                }
                if (!websiteValid)
                {
                    ModelState.AddModelError("Website", AppGlobal.Language.GetText(this, "WebsiteNotValid", "Please enter a valid Url"));
                }
            }

            CheckMaxNumberOfLocations(provider);

            if (ModelState.IsValid)
            {
                Location location = CreateFromModel(model, provider.ProviderId);
                if (!location.Address.Latitude.HasValue)
                {
                    ModelState.AddModelError("Address.Postcode", unableToFindLatLngMessage);
                }
                else
                {
                    return Json(new LocationJsonModel(location));
                }
            }

            // Populate drop downs
            GetLookups(model);

            // Set this to true here so that the message doesn't appear twice
            ViewBag.CanProviderCreateNewLocation = true;

            return View("Create", model);
        }

        [NonAction]
        private Location CreateFromModel(AddEditLocationModel model, Int32 providerId)
        {
            Location location = model.ToEntity(db);
            location.ProviderId = providerId;
            location.RecordStatusId = (Int32) Constants.RecordStatus.Live;
            Address locationAddress = model.Address.ToEntity(db);
            location.Address = locationAddress;
            if (locationAddress.Latitude.HasValue)
            {
                db.Addresses.Add(locationAddress);
                db.Locations.Add(location);
                db.SaveChanges();
            }

            return location;
        }

        [HttpGet]
        [PermissionAuthorize(Permission.PermissionName.CanEditProviderLocation)]
        [ContextAuthorize(UserContext.UserContextName.Provider)]
        public ActionResult Edit(Int32? id)
        {
            Provider provider = db.Providers.Find(userContext.ItemId);
            if (provider == null)
            {
                return HttpNotFound();
            }

            Location location = db.Locations.Include("Address").FirstOrDefault(x => x.LocationId == id);
            if (location == null || location.ProviderId != userContext.ItemId)
            {

ProviderPortal/Views/Location/Create.cshtml
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.AddEditLocationModel

@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "Add New Location");
    Layout = Model.IsInDialog ? "" : "~/Views/Shared/_Layout.cshtml";
}

@if (!Model.IsInDialog)
{
    <h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "Add New Location")</h2>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()    

    <div class="form-horizontal">
        <h4>@AppGlobal.Language.GetText(this, "SubHeader", "")</h4>
        <hr />

        @if (!ViewBag.CanProviderCreateNewLocation)
        {
            <div class="alert alert-danger">
                @Html.Raw(String.Format(AppGlobal.Language.GetText(this, "MaxNumberOfLocationsReached", "You have reached the maximum number of locations allowed ({0}).  If you require more locations please contact our helpdesk."), ViewBag.MaxNumberOfLocations))
            </div>
        }

        @Html.EditableDataValidationSummary(false)

        @Html.RequiredFields(new { @class = "col-md-offset-2" })

        @Html.HiddenFor(m => m.ProviderId)

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.ProviderOwnLocationRef, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderOwnLocationRef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderOwnLocationRef)
            </div>
        </div>

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.LocationName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationName)
            </div>
        </div>

        <fieldset>
            <legend>@AppGlobal.Language.GetText(this, "AddressHeader", "Address Details")</legend>
            @Html.EditorFor(m => m.Address, "_EditLocationAddressPartial")
        </fieldset>

        <fieldset>
            <legend>@AppGlobal.Language.GetText(this, "ContactDetailsHeader", "Contact Details")</legend>

            <div class="form-group">
                @Html.LanguageLabelFor(model => model.Telephone, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telephone)
                </div>
            </div>

            <div class="form-group">
                @Html.LanguageLabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LanguageLabelFor(model => model.Website, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control", data_url = "true" } })
                    @Html.ValidationMessageFor(model => model.Website)
                </div>
            </div>
        </fieldset>

        @if (!Model.IsInDialog)
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@AppGlobal.Language.GetText(this, "Submit", "Create")" class="btn btn-success" />
                </div>
            </div>
        }
    </div>

    if (Model.IsInDialog)
    {
        @Html.Partial("_ChooseAddressScript")
        <script>
            $('.modal-dialog .glyphicon-question-sign').tooltip({ placement: "auto" });
        </script>
    
        <style>
            .modal-dialog {
                width: 620px
            }
        </style>
    }
}

ProviderPortal/Views/Location/Edit.cshtml
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.AddEditLocationModel

@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "Edit Location");
}

<h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "Edit Location")</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@AppGlobal.Language.GetText(this, "SubHeader", "")</h4>
        <hr />

        @if (Model.RecordStatusId == (Int32) Constants.RecordStatus.Archived)
        {
            <div class="col-md-offset-2 warning">
                @Html.Raw(AppGlobal.Language.GetText(this, "LocationArchivedWarning", "<strong>Warning:</strong> this Location is currently <strong>ARCHIVED</strong>."))
            </div>
        }

        @Html.EditableDataValidationSummary(false)        
        @Html.HiddenFor(model => model.LocationId)
        @Html.HiddenFor(m => m.ProviderId)

        @Html.RequiredFields(new {@class = "col-md-offset-2"}) 

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.ProviderOwnLocationRef, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderOwnLocationRef, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.ProviderOwnLocationRef)
            </div>
        </div>

        <div class="form-group">
            @Html.LanguageLabelFor(model => model.LocationName, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LocationName)
            </div>
        </div>

        <fieldset>
            <legend>@AppGlobal.Language.GetText(this, "AddressHeader", "Address Details")</legend>
            @Html.EditorFor(m => m.Address, "_EditLocationAddressPartial")
        </fieldset>

        <fieldset>
            <legend>@AppGlobal.Language.GetText(this, "ContactDetailsHeader", "Contact Details")</legend>

            <div class="form-group">
                @Html.LanguageLabelFor(model => model.Telephone, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telephone, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Telephone)
                </div>
            </div>

            <div class="form-group">
                @Html.LanguageLabelFor(model => model.Email, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LanguageLabelFor(model => model.Website, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Website, new {htmlAttributes = new {@class = "form-control", data_url = "true"}})
                    @Html.ValidationMessageFor(model => model.Website)
                </div>
            </div>
        </fieldset>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@AppGlobal.Language.GetText(this, "Submit", "Save")" class="btn btn-success" />
                @if (Model.RecordStatusId != (Int32) Constants.RecordStatus.Archived)
                {
                    <input id="btnArchive" type="button" name="Archive" value="@AppGlobal.Language.GetText(this, "Archive", "Archive")" class="btn btn-default" />
                }
                else
                {
                    <input id="btnUnarchive" type="button" name="Unarchive" value="@AppGlobal.Language.GetText(this, "Unarchive", "Unarchive")" class="btn btn-default" />
                }
                @if (Permission.HasPermission(false, false, Permission.PermissionName.CanDeleteProviderLocation))
                {
                    <input id="btnDelete" type="button" name="Delete" value="@AppGlobal.Language.GetText(this, "Delete", "Delete")" class="btn btn-default" />
                }
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function() {

            $("#btnArchive").click(function() {
                if (confirm('@AppGlobal.Language.GetText(this, "ArchiveLocationWarning", "Are you sure you would like to archive this Location?")') === false) {
                    return;
                }

                // Check if there are any apprenticeships for this Location
                var url = '@Url.Action("GetApprenticeships", "Location", new {Id = @Model.LocationId})';
                $.ajax({
                    url: url,
                    success: function(result) {
                        var archiveApprenticeships = false;
                        if (result.length != 0) {
                            archiveApprenticeships = confirm("@AppGlobal.Language.GetText(this, "ArchiveApprenticeshipsForLocation", "You have apprenticeships attached to this Location, would you like to archive these also?")");
                        }
                        url = '@Url.Action("Archive", "Location", new {Id = @Model.LocationId, ArchiveApprenticeships = "__ArchiveApprenticeships__"})';
                        url = url.replace('__ArchiveApprenticeships__', archiveApprenticeships);
                        $.ajax({
                            url: url,
                            success: function() {
                                if (archiveApprenticeships) {
                                    window.location.reload(true);
                                } else {
                                    alert("@AppGlobal.Language.GetText(this, "ReAssignLocationsForApprenticeships", "Please re-assign locations to these apprenticeships")");
                                    window.location.replace("@Url.Action("List", "Apprenticeship", new { LocationId = Model.LocationId })");
                                }
                            },
                            error: function() {
                                alert("Error archiving Location");
                            },
                            cache: false,
                            type: 'POST',
                            contentType: 'application/x-www-form-urlencoded, charset=utf-8'
                        });
                    },
                    error: function() {
                        alert("Error archiving Location");
                    },
                    cache: false,
                    type: 'POST',
                    contentType: 'application/json, charset=utf-8',
                    dataType: 'json'
                });
            });

            $("#btnUnarchive").click(function() {
                var url = '@Url.Action("Unarchive", "Location", new {Id = @Model.LocationId})';
                $.ajax({
                    url: url,
                    success: function() {
                        window.location.reload(true);
                    },
                    error: function() {
                        alert("Error unarchiving Location");
                    },
                    cache: false,
                    type: 'POST',
                    contentType: 'application/x-www-form-urlencoded, charset=utf-8'
                });
            });

            $("#btnDelete").click(function() {
                if (confirm('@AppGlobal.Language.GetText(this, "DeleteLocationWarning", "Are you sure you would like to delete this Location?  Any apprenticeship delivery locations attached to this Location will be deleted.")') === false) {
                    return;
                }
                var url = '@Url.Action("Delete", "Location", new {Id = @Model.LocationId})';
                $.ajax({
                    url: url,
                    success: function() {
                        window.location.replace("@Url.Action("List", "Location")");
                    },
                    error: function() {
                        alert("Error deleting location");
                    },
                    cache: false,
                    type: 'POST',
                    contentType: 'application/x-www-form-urlencoded, charset=utf-8'
                });
            });

        });

    </script>
}

ProviderPortal/Views/Location/List.cshtml
@model Tribal.SkillsFundingAgency.ProviderPortal.Models.LocationSearchModel
@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "View all Locations");
}

<div class="col-md-12" style="padding-left: 0px; padding-right: 0px;">
    <div class="col-md-10" style="padding-left: 0px; padding-right: 0px;">
        <h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "View all Locations")</h2>
    </div>
    @if (Permission.HasPermission(false, false, Permission.PermissionName.CanAddProviderLocation))
    {
        <div class="col-md-2 text-right" style="padding-left: 0px; padding-right: 0px;">
            <div style="margin-top: 18px; margin-bottom: 8px;">
                <a href="@Url.Action("Create", "Location", null)" class="btn btn-apprenticeship">@AppGlobal.Language.GetText(this, "AddLocation", "Add Location")</a>
            </div>
        </div>
    }
</div>

@Html.DisplayFor(m => m.Locations, "_ListLocations")

ProviderPortal/Views/Location/UnableToCreate.cshtml
@{
    Layout = "";
}
<div style="color: red;">
    @Html.Raw(AppGlobal.Language.GetText(this, "UnableToCreateLocationProviderContextChanged", "Unable to create a new location.  The provider context has changed."))
</div>

ProviderPortal/Views/Location/View.cshtml
@using Tribal.SkillsFundingAgency.ProviderPortal.Models
@model ViewLocationModel
@{
    ViewBag.Title = AppGlobal.Language.GetText(this, "Title", "Location Details");
}

<h2 class="apprenticeships">@AppGlobal.Language.GetText(this, "Header", "Location Details")</h2>
<h3>@Model.LocationName</h3>
<hr/>
<div class="col-md-12">
        
    @if (Model.RecordStatusId == (Int32)Constants.RecordStatus.Archived)
    {
        <div class="col-md-offset-2 warning">
            @Html.Raw(AppGlobal.Language.GetText(this, "LocationArchivedWarning", "<strong>Warning:</strong> this Location is currently <strong>ARCHIVED</strong>."))
        </div>
    }

    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(m => m.RecordStatusId)</dt>
        <dd>@Html.DisplayTextFor(m => m.RecordStatusName)</dd>
    
        <dt>@Html.DisplayNameFor(m => m.ProviderOwnLocationRef)</dt>
        <dd>@Html.DisplayFor(m => m.ProviderOwnLocationRef)</dd>

        <dt>@Html.DisplayNameFor(m => m.LocationName)</dt>
        <dd>@Html.DisplayTextFor(m => m.LocationName)</dd>    
    
        <dt>@Html.DisplayNameFor(m => m.Address)</dt>
        <dd>@Html.Raw(Model.Address.GetMultipleLineHTMLAddress())</dd>

        <dt>@Html.DisplayNameFor(m => m.Telephone)</dt>
        <dd>@Html.DisplayTextFor(m => m.Telephone)</dd>

        <dt>@Html.DisplayNameFor(m => m.Email)</dt>
        <dd>@Html.DisplayTextFor(m => m.Email)</dd>    
        
        <dt>@Html.DisplayNameFor(m => m.Website)</dt>
        <dd>
            @if (Model.Website != null)
            {
                var prefix = Model.Website.Contains("://") ? "" : "http://";
                <a href="@prefix@Model.Website" target="_blank">@Model.Website</a>
            }
        </dd>
    
    </dl>

</div>